/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegrasClassificacaoRouteImport } from './routes/regras-classificacao'
import { Route as BaseBaseIdRouteImport } from './routes/base.$baseId'
import { Route as MetricaMetricaIdRouteImport } from './routes/metrica.$metricaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasClassificacaoRoute = RegrasClassificacaoRouteImport.update({
  id: '/regras-classificacao',
  path: '/regras-classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseBaseIdRoute = BaseBaseIdRouteImport.update({
  id: '/base/$baseId',
  path: '/base/$baseId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricaMetricaIdRoute = MetricaMetricaIdRouteImport.update({
  id: '/metrica/$metricaId',
  path: '/metrica/$metricaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/regras-classificacao': typeof RegrasClassificacaoRoute
  '/base/$baseId': typeof BaseBaseIdRoute
  '/metrica/$metricaId': typeof MetricaMetricaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/regras-classificacao': typeof RegrasClassificacaoRoute
  '/base/$baseId': typeof BaseBaseIdRoute
  '/metrica/$metricaId': typeof MetricaMetricaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/regras-classificacao': typeof RegrasClassificacaoRoute
  '/base/$baseId': typeof BaseBaseIdRoute
  '/metrica/$metricaId': typeof MetricaMetricaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/regras-classificacao' | '/base/$baseId' | '/metrica/$metricaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/regras-classificacao' | '/base/$baseId' | '/metrica/$metricaId'
  id:
    | '__root__'
    | '/'
    | '/regras-classificacao'
    | '/base/$baseId'
    | '/metrica/$metricaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegrasClassificacaoRoute: typeof RegrasClassificacaoRoute
  BaseBaseIdRoute: typeof BaseBaseIdRoute
  MetricaMetricaIdRoute: typeof MetricaMetricaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras-classificacao': {
      id: '/regras-classificacao'
      path: '/regras-classificacao'
      fullPath: '/regras-classificacao'
      preLoaderRoute: typeof RegrasClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/$baseId': {
      id: '/base/$baseId'
      path: '/base/$baseId'
      fullPath: '/base/$baseId'
      preLoaderRoute: typeof BaseBaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrica/$metricaId': {
      id: '/metrica/$metricaId'
      path: '/metrica/$metricaId'
      fullPath: '/metrica/$metricaId'
      preLoaderRoute: typeof MetricaMetricaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegrasClassificacaoRoute: RegrasClassificacaoRoute,
  BaseBaseIdRoute: BaseBaseIdRoute,
  MetricaMetricaIdRoute: MetricaMetricaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
